### ISSUE TITLE
Get STAC Browser working inside Navbar

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-sds-portal#10]
depends on: https://github.com/unity-sds/unity-data-services/issues/292

**Comment by rtapella** [comment]
relates to "figure out CORS stuff" https://github.com/unity-sds/unity-ui/issues/6

**Comment by rtapella** [comment]
@wphyojpl what info do you need from us to configure STAC Browser to be happy with CORS requests from the navbar UI to STAC Browser?

Can we read the locations from SSM?

**Comment by wphyojpl** [comment]
Probably just the domain name so that it can be added to CORS.

**Comment by GodwinShen** [comment]
@rtapella and @wphyojpl ping for status.

**Comment by wphyojpl** [comment]
Hi @GodwinShen 
Blocked by UCS' login page

**Comment by rtapella** [comment]
@wphyojpl as long as STAC Browser is sending health information to the health service, it'll be displayed

**Comment by wphyojpl** [comment]
Actually, there is an update from Ramesh. 
Stac Browser will need to find the token passed by httpd login page. 

I'm not sure if that is the same as showing Stac browser in nav bar.

**Comment by rtapella** [comment]
It is related. We will need to work this out because the iframe will need to get the token

**Comment by rtapella** [comment]
We should have a quick meeting to talk about how this could work with full-page as well as in an iframe.
@wphyojpl @anilnatha

**Comment by rtapella** [comment]
@wphyojpl we will need the stac browser health-endpoint URL to have the MCP URL
then it should show up in the navbar and work properly

**Comment by rtapella** [comment]
this should be pretty close, I think

**Comment by rtapella** [comment]
also add stac browser to the navbar in the emit-dev and unity-ops venues. it is a shared service.
https://www.mdps.mcp.nasa.gov:4443/data/stac_browser/

**Comment by rtapella** [comment]
This works
