### ISSUE TITLE
Set up a Unity web server for landing page, navbar, job GUI etc.

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-sds-portal#6]

**Comment by anilnatha** [comment]
If landing page refers to the initial page someone sees after login, that still needs to be worked, but without stating the obvious, navbar and job GUI are "done" based on past iterations, but will evolve as we move into the marketplace.

**Comment by anilnatha** [comment]
@rtapella I think we should close this ticket and create a ticket fro the landing page that has specific changes that we need for it.

I don't have the ability to close this ticket, only add comments

**Comment by anilnatha** [comment]
I don't have the ability to close this ticket, only add comments
