### ISSUE TITLE
[Feature] Put navbar UI into the Marketplace

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-sds-portal#9]
Tom Barber is point of contact for questions

Documentation:
https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/users-guide/deployment/deployment-concepts-and-infrastructure/unity-marketplace

**Comment by rtapella** [comment]
https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/users-guide/deployment/deployment-concepts-and-infrastructure/unity-marketplace

**Comment by rtapella** [comment]
from Galen:
I think steps 1-6 are pretty solid though, so you could go ahead and start on that work, and reach out to us as necessary

I think theoretically, if you get components [into here](https://github.com/unity-sds/unity-marketplace/tree/main/applications), then they will show up in the management console.

**Comment by rtapella** [comment]
part of https://github.com/unity-sds/unity-project-management/issues/74

**Comment by GodwinShen** [comment]
@rtapella Can we get an update on this ticket?  I see that this is now part of sprint 24.1.2.

**Comment by rtapella** [comment]
In progress. Needs some additional help from Galen & Tom to configure properly. (moved to 24.1.3)

**Comment by rtapella** [comment]
things that need to work for this to be Done
- [x] set up Terraform to handle deployment for marketplace
- [ ] configuration of the app for marketplace

**Comment by GodwinShen** [comment]
@rtapella any updates?  Do we think we will complete this work in the current 24.1.3 sprint?

**Comment by anilnatha** [comment]
Still in work as there is lots to do. Met with Galen/Tom on February the 16th to get clarity on challenges we were facing. With the short/holiday week we had last week didn't have enough time to complete the work. We originally expected this task to take 2-3 sprints to complete because the market place is new territory for us.

cc: @rtapella @GodwinShen

**Comment by rtapella** [comment]
Had another meeting March 11 to work through some details.

**Comment by GodwinShen** [comment]
@rtapella and @anilnatha any update on this one?  I see you all had a meeting on 3/11, any progress since then?

**Comment by anilnatha** [comment]
@GodwinShen I'm continuing work on this ticket. Galen and I met last Thursday afternoon and we were able to get the initial Marketplace configuration needed for unity-ui. I'm now working on the terrafrom configuration to "install" the unity-ui application into marketplace.

**Comment by galenatjpl** [comment]
@rtapella I think this ticket should be assigned to a sprint near the end of the 24.2 PI.  I would move it, but you are the creator of this.

**Comment by rtapella** [comment]
@anilnatha what do you think? I put it in sprint 4 for now.
This is the Feature so it's kind of the bucket for all the stuff related to putting the navbar in marketplace and also hooking it up.

**Comment by rtapella** [comment]
The app is deployable.

Until we get a cookie set up, the site just shows a blank page once you log in

**Comment by GodwinShen** [comment]
@galenatjpl and @anilnatha will setup a hackathon to knock this one out.

**Comment by anilnatha** [comment]
We made great progress today! We solved the issues we had with our inability to deploy the UI using the marketplace. The main issue was that the older marketplace UI had presented a field named `branch` that implied one could provide a repo branch to pull our infrastructure's terraform from, but the branch didn't work and it was really just looking in `main` and executing that code. After merging our code to our repos `main` branch we were able to deploy the UI using Marketplace in one of Brad's project accounts.

Next step is to await an update of the Unity_Venue_Dev's marketplace instance that has the latest marketplace UI updaates and test the installation once more. With this working, @rtapella and I can begin testing how future updates are deployed and also provide UI/UX support to Galen's team to further improve the marketplace UI.

Big thanks to @galenatjpl @hargitayjpl @jpl-btlunsfo @ramesh-maddegoda for helping us get this working! 🎉

**Comment by rtapella** [comment]
- Waiting for update to unity-venue-dev 
- Anil talked to Galen on Nov 4
- @galenatjpl

**Comment by rtapella** [comment]
- may be able to auto-load navbar into a new venue pretty easily, see: https://github.com/unity-sds/unity-cs/issues/483

**Comment by galenatjpl** [comment]
@anilnatha @rtapella The plan is to redeploy unity-venue-dev this afternoon (11/6), then you guys can test again.
The autoloading part will come a bit later, but I may start testing that soon.

**Comment by anilnatha** [comment]
We have verified that the installation of the UI using the management console is working in the Unity_Venue_Dev account.
